### ISSUE TITLE
[BUG] Can't unmute an alert

### ISSUE THREAD

**Issue by tpoindessous** [mvisonneau/terraform-provider-updown#3]
Hi !

We use your provider and first, we would like to thank you for your work.

We added some URL checks with TF and we forgot to add a special string match for URL which responds with 404.

So, while waiting for modifying TF, we muted these alarm in "forever" mode.

Then, we added the special string match : 
```
  mute_until:   "forever" => ""
  string_match: "" => "Sorry"
```

Updown reported that our website is now OK, but the alarm was still muted forever.
We re-launched TF and one change was needed
```
  mute_until: "forever" => ""
```

This change doesn't work and we can't unmute an alarm with TF. We need to use the website.

Thanks !

**Comment by mvisonneau** [comment]
@tpoindessous thanks! I haven't taken the time to reproduce yet but I just released a new version which is now using the latest SDK version from @antoineaugusti. It should be containing this fix which might be related to what you were describing https://github.com/AntoineAugusti/updown/pull/9/files

Would you mind retrying?

**Comment by AntoineAugusti** [comment]
If it's still not fixed please open up an issue (and a PR if you can!) upstream 😉
