### ISSUE TITLE
Provide a new binary for releases

### ISSUE THREAD

**Issue by nlamirault** [mvisonneau/terraform-provider-updown#33]
Hi 
could you provide binaries for releases ? 
This can be quite useful for CI / CD jobs.

**Comment by mvisonneau** [comment]
👋 hey @nlamirault, indeed, I released a [new version with artifacts](https://github.com/mvisonneau/terraform-provider-updown/releases/tag/v0.2.1). I also pushed it to the the terraform registry to make it even easier to integrate with TF >= 0.13 : https://registry.terraform.io/providers/mvisonneau/updown/latest

```hcl
terraform {
  required_providers {
    updown = {
      source = "mvisonneau/updown"
      version = "0.2.1"
    }
  }
}
```

**Comment by nlamirault** [comment]
Great ! It works perfectly. Thanks.
