### ISSUE TITLE
Documentation for import check

### ISSUE THREAD

**Issue by nlamirault** [mvisonneau/terraform-provider-updown#36]
Could you provide documentation how to import existing "check" from updown.io.
Thanks

**Comment by mvisonneau** [comment]
This will be part of the documentation when I will be done but it is basically

```
terraform import updown_check.my_website <check_id>
```

The `check_id` is basically whatever **4 characters** you have after **https://updown.io/** 
I believe it looks like the following regexp : `^https:\/\/updown.io\/([a-z0-9]{4})$` 🤷
