### ISSUE TITLE
Invite to publish to the Terraform Registry

### ISSUE THREAD

**Issue by aicarmic** [mvisonneau/terraform-provider-updown#38]
👋  Hi there! We noticed this provider is on our list of community providers, however it has not yet been published to the newly-released Terraform Registry for Providers (registry.terraform.io). We'd like to invite you to get it published, since it makes using and installing it much easier for anyone using Terraform 0.13! Instructions for doing so are available [here](https://www.terraform.io/docs/registry/providers/publishing.html). If you need some help producing documentation, take a look at [this project](https://github.com/hashicorp/terraform-plugin-docs) which might come in handy!

Please note that we will soon be redirecting the [community listing page](https://www.terraform.io/docs/providers/type/community-index.html) to registry.terraform.io.

Thanks for your contributions and we look forward to seeing this provider listed soon!

Thanks,
Team Terraform @ HashiCorp

**Comment by mvisonneau** [comment]
👋 hey @aicarmic, indeed I still need to rewrite the documention in your expected format! I believed it was already published though: https://registry.terraform.io/providers/mvisonneau/updown/latest

Aside of the missing doc, isn't it already functionnal for people willing to use it through the new approach? 🤔

**Comment by aicarmic** [comment]
Hi @mvisonneau oh great! May have missed this as we were looking, apologies for that. Thanks for getting it published!
